contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'
urlpatterns = [
    path('', views.Contact.as_view(), name='contact'),
]

demodj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('blog/', include('post.urls')),
    path('contact/', include('contact.urls')),
]

home/urls.py
from . import views
from django.urls import path

app_name = 'home'
urlpatterns = [
    path('', views.index, name='home')
]

post/urls.py
from django.urls import path, include
from . import views

app_name = 'post'
urlpatterns = [
    path('', views.post, name='blog'),
    path('<int:id>/', views.postDetail, name='postDetail'),
]

contact/models.py
from django.db import models

# Create your models here.
class ContactForm(models.Model):
    username = models.CharField(max_length=25)
    email = models.EmailField()
    body = models.TextField()

    def __str__(self):
        return self.username

home/models.py
from django.db import models

# Create your models here.

post/models.py
from django.db import models

# Create your models here.
class PostForm(models.Model):
    title = models.CharField(max_length= 255)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

contact/forms.py
from django import forms
from .models import ContactForm


class Contact_Form(forms.Form):
    username = forms.CharField(max_length=25)
    email = forms.EmailField()
    body = forms.CharField(widget=forms.Textarea)

contact/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .forms import Contact_Form
from .models import ContactForm
from django.views import View

# Create your views here.
class Contact(View):

    def get(self, request):
        cf = Contact_Form
        return render(request, 'contact/contact.html', {'cf': cf})


    def post(self, request):
        if request.method == 'POST':
            cf = Contact_Form(request.POST)
            if cf.is_valid():
                saveCF = ContactForm(username=cf.cleaned_data['username'],
                                     email=cf.cleaned_data['email'],
                                     body=cf.cleaned_data['body'])
                saveCF.save()
                return HttpResponse('save success')
        else:
            return HttpResponse('not POST')

home/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'home/index.html')

post/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import PostForm
# Create your views here.

def post(request):
    pf = PostForm.objects.all()
    return render(request, 'post/post.html', {'pf': pf})


def postDetail(request, id):
    pd = PostForm.objects.get(id=id)
    return render(request, 'post/detail.html', {'pd': pd})

contact/templates/contact/contact.html
{% extends 'home/base.html' %}
{% block content %}
    <form action="{% url 'contact:contact' %}" method="post">
        {% csrf_token %}
        {{ cf }}
        <input type="submit" value="Gửi">
    </form>
{% endblock %}

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'home/style.css' %}">
</head>
<body>
    <div class="menu">
        <ul>
            <li><a href="{% url 'home:home' %}">Home</a></li>
            <li><a href="{% url 'post:blog' %}">Blog</a></li>
            <li><a href="#">Product</a></li>
            <li><a href="{% url 'contact:contact' %}">Contact</a></li>
        </ul>
    </div>
<div class="content">
    {% block content %}
    	
    {% endblock %}
</div>
</body>
</html>

home/templates/home/index.html
{% extends 'home/base.html' %}
{% block content %}
    <h2>Home Page</h2>
{% endblock %}

post/templates/post/detail.html
{% extends 'home/base.html' %}
{% block content %}
	{{ pd.title }}
    {{ pd.body }}
{% endblock %}

post/templates/post/post.html
{% extends 'home/base.html' %}
    {% block content %}
    	{% for item in pf %}
    		<p><a href="{% url 'post:postDetail' item.id %}">{{ item.title }}</a></p>
    	{% endfor %}

    {% endblock %}